"""The models and the migrations must not drift apart.

Tests build their schema straight from the models; the running service builds
it from migrations. That is fast and convenient right up until the two stop
describing the same database, at which point every test passes and production
breaks. This is the only thing standing between those two worlds.
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from sqlalchemy import MetaData, create_engine

from friday.store import schema

ROOT = Path(__file__).resolve().parent.parent


def test_the_models_and_the_migrations_describe_the_same_database(tmp_path):
    path = tmp_path / "fresh.db"
    subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=ROOT,
        env={**os.environ, "FRIDAY_DB": str(path)},
        check=True,
        capture_output=True,
    )

    engine = create_engine(f"sqlite:///{path}")
    with engine.connect() as connection:
        context = MigrationContext.configure(
            connection, opts={"render_as_batch": True}
        )
        assert compare_metadata(context, schema.Base.metadata) == []
        _assert_primary_keys_match(connection)
        _assert_partial_index_predicates_match(connection)


def _assert_partial_index_predicates_match(connection) -> None:
    """`compare_metadata` does not report a changed partial-index predicate
    either, and autogenerate emits an empty revision for one.

    Found on board `read-it-the-way-the-operator-does`, ticket 09's review:
    taking `finding` out of `uq_memories_active_key` changed the model's
    `sqlite_where` and autogenerated `pass`. A database migrated that way
    still refuses a second finding on one key while every test — built from
    the models — accepts it.
    """
    live = {
        name: sql
        for name, sql in connection.exec_driver_sql(
            "SELECT name, sql FROM sqlite_master WHERE type = 'index'"
        )
    }
    for table in schema.Base.metadata.tables.values():
        for index in table.indexes:
            where = index.dialect_options["sqlite"]["where"]
            if where is None:
                continue
            expected = " ".join(str(where).split())
            actual = " ".join(live[index.name].split(" WHERE ", 1)[1].split())
            assert actual == expected, f"{index.name} predicate drifted: {actual!r}"


def _assert_primary_keys_match(connection) -> None:
    """`compare_metadata` does not report a changed primary key.

    Verified: swapping the `messages` key from (provider, provider_message_id)
    to provider_message_id alone leaves the diff empty. Alembic will not
    autogenerate that change either, so the guard has to check it directly or
    the one drift that silently breaks deduplication goes unnoticed.
    """
    live = MetaData()
    live.reflect(bind=connection)
    for name, table in schema.Base.metadata.tables.items():
        expected = [c.name for c in table.primary_key.columns]
        actual = [c.name for c in live.tables[name].primary_key.columns]
        assert actual == expected, f"{name} primary key drifted: {actual} != {expected}"


def test_migrating_does_not_switch_the_applications_logging_off(tmp_path):
    """Alembic's own config sets the root logger to WARNING and disables every
    existing logger. From the CLI that is what you want. Called from inside the
    app it silences the agent, which looks exactly like an agent receiving
    nothing — and that is how it was found."""
    import run_agent

    root = logging.getLogger()
    before = (root.level, list(root.handlers))
    logging.basicConfig(level=logging.DEBUG, force=True)
    os.environ["FRIDAY_DB"] = str(tmp_path / "logging.db")
    try:
        run_agent.migrate()

        assert logging.getLogger("friday.kernel.inbox").isEnabledFor(logging.DEBUG)
    finally:
        os.environ.pop("FRIDAY_DB", None)
        logging.basicConfig(level=before[0], force=True)
        root.handlers[:] = before[1]


def test_a_migration_that_already_half_applied_can_still_finish(tmp_path):
    """This happened to the live database and stopped the service booting.

    `original_text` was added and made NOT NULL, then the backfill and the
    version stamp did not run — SQLite DDL was outside a transaction, so a
    failure partway left the schema ahead of the stamp. Every subsequent start
    then died on `duplicate column name: original_text`, before anything
    opened the database. `env.py` runs migrations transactionally now, and
    this migration can finish the job it left half done.
    """
    import subprocess
    import sqlite3

    db = tmp_path / "half.db"
    env = {**os.environ, "FRIDAY_DB": str(db)}

    def alembic(*args):
        return subprocess.run(
            ["uv", "run", "alembic", *args],
            cwd=ROOT, env=env, capture_output=True, text=True,
        )

    # The state the live database was in: one revision short, with that
    # revision's column already present and its backfill never run.
    alembic("upgrade", "71a2c91fa3b0")
    with sqlite3.connect(db) as raw:
        raw.execute(
            "INSERT INTO messages (provider, provider_message_id, conversation_id,"
            " author_id, author_name, text, created_at, is_own, channel_id)"
            " VALUES ('discord','1','discord:c','u','someone','api bị lỗi rồi',"
            "'2026-09-01T00:00:00+00:00',0,'c')"
        )
        raw.execute("ALTER TABLE messages ADD COLUMN original_text TEXT")

    done = alembic("upgrade", "head")
    assert done.returncode == 0, done.stderr

    with sqlite3.connect(db) as raw:
        text, original = raw.execute(
            "SELECT text, original_text FROM messages"
        ).fetchone()
        assert original == text, "the backfill that never ran did not run now"


def _alembic(path, *args) -> None:
    subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=ROOT,
        env={**os.environ, "FRIDAY_DB": str(path)},
        check=True,
        capture_output=True,
    )


def test_an_approved_task_carries_its_approval_onto_its_reply_rows(tmp_path):
    """Approval moved from the task to the row (board
    read-it-the-way-the-operator-does, ticket 12). A reply the operator
    approved before the move must still be approved after it — and nothing
    else may become approved by the move: not the card that asked, and not
    another task's reply."""
    path = tmp_path / "carried.db"
    _alembic(path, "upgrade", "a423973bc96d")

    engine = create_engine(f"sqlite:///{path}")
    live = MetaData()
    live.reflect(bind=engine)
    tasks, outbox = live.tables["tasks"], live.tables["outbox"]
    common = dict(conversation_id="discord:1", state="queued", attempts=0,
                  created_at="2026-09-01T00:00:00+00:00", sender="discord_user")
    with engine.begin() as connection:
        connection.execute(tasks.insert(), [
            dict(id=1, conversation_id="discord:1", type="backend.trace_problem", state="review",
                 confidence=0.9, params={}, created_at="2026-09-01T00:00:00+00:00",
                 approved_at="2026-09-02T00:00:00+00:00", approved_by="longle_"),
            dict(id=2, conversation_id="discord:1", type="backend.trace_problem", state="review",
                 confidence=0.9, params={}, created_at="2026-09-01T00:00:00+00:00",
                 approved_at=None, approved_by=None),
        ])
        connection.execute(outbox.insert(), [
            dict(id=10, task_id=1, kind="reply", text="đang xử lý", **common),
            dict(id=11, task_id=1, kind="approval_card", text="đang xử lý", **common),
            dict(id=20, task_id=2, kind="reply", text="chưa duyệt", **common),
        ])
    engine.dispose()

    _alembic(path, "upgrade", "head")

    engine = create_engine(f"sqlite:///{path}")
    live = MetaData()
    live.reflect(bind=engine)
    outbox = live.tables["outbox"]
    with engine.connect() as connection:
        rows = {
            r.id: (r.approved_at, r.approved_by)
            for r in connection.execute(outbox.select())
        }
    assert rows == {
        10: ("2026-09-02T00:00:00+00:00", "longle_"),
        11: (None, None),
        20: (None, None),
    }


def _task_params(path) -> dict[int, tuple[str, str]]:
    """`json_type` rather than decoding: a dict stored as a JSON string decodes
    to a `str` through `sa.JSON`, and that is exactly the drift to catch."""
    engine = create_engine(f"sqlite:///{path}")
    with engine.connect() as connection:
        rows = connection.exec_driver_sql(
            "SELECT id, json_type(params), json_extract(params, '$.curl')"
            " FROM tasks ORDER BY id"
        ).all()
    engine.dispose()
    return {row[0]: (row[1], row[2]) for row in rows}


def _insert_task(path, id: int, params) -> None:
    engine = create_engine(f"sqlite:///{path}")
    live = MetaData()
    live.reflect(bind=engine)
    with engine.begin() as connection:
        connection.execute(live.tables["tasks"].insert(), [
            dict(id=id, conversation_id="discord:1", type="backend.trace_problem",
                 state="needs_human", confidence=0.9, params=params,
                 created_at="2026-09-01T00:00:00+00:00"),
        ])
    engine.dispose()


def test_scrubbing_a_credential_leaves_the_params_an_object(tmp_path):
    """`b7c1a4e93f02` wrote `json.dumps(cleaned)` into a `sa.JSON` column,
    which encodes again: every task it scrubbed came back as a JSON string,
    and the pool died on `'str' object has no attribute 'items'` at boot."""
    path = tmp_path / "scrubbed.db"
    _alembic(path, "upgrade", "f81f63e7d3ce")
    _insert_task(path, 1, {"curl": "curl -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.c2lnbmF0dXJl' https://x"})
    _insert_task(path, 2, {"summary": "nothing to scrub"})

    # Not `head`: the repair after it would hide this revision's own bug.
    _alembic(path, "upgrade", "b7c1a4e93f02")

    params = _task_params(path)
    assert params[1][0] == "object"
    assert "[REDACTED]" in params[1][1] and "eyJ" not in params[1][1]
    assert params[2] == ("object", None)


def test_params_the_scrub_double_encoded_are_objects_again(tmp_path):
    """The live database already ran `b7c1a4e93f02` as it was: fixing that
    revision does not reach rows it has written. This is the state tasks 4 and
    6 were in on 2026-09-21."""
    path = tmp_path / "double.db"
    _alembic(path, "upgrade", "b7c1a4e93f02")
    _insert_task(path, 4, '{"curl": "curl [REDACTED]", "summary": "x"}')
    _insert_task(path, 5, {"summary": "untouched"})
    _insert_task(path, 7, "not json")

    _alembic(path, "upgrade", "head")

    assert _task_params(path) == {
        4: ("object", "curl [REDACTED]"),
        5: ("object", None),
        7: ("text", None),
    }
