"""one invoke in the runner

Board read-it-the-way-the-operator-does, ticket 11. `node_runs` holds one row
per attempt at one graph node, written by `DAGRunner._invoke`. `dag_state`
gains `dag_version` — a digest of the graph's shape — so a renamed or
reordered node cannot inherit a result recorded under the old shape. Existing
rows get NULL, which matches no version: they are discarded, not trusted.

Revision ID: 37048e489fc1
Revises: c2b3bbe390ee
Create Date: 2026-09-18 15:22:49.623635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37048e489fc1"
down_revision: str | Sequence[str] | None = "c2b3bbe390ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("dag_name", sa.String(), nullable=False),
        sa.Column("dag_version", sa.String(), nullable=False),
        sa.Column("node", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("node_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_node_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_node_runs_task_id"), ["task_id"], unique=False
        )

    with op.batch_alter_table("dag_state", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dag_version", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dag_state", schema=None) as batch_op:
        batch_op.drop_column("dag_version")

    with op.batch_alter_table("node_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_node_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_node_runs_created_at"))

    op.drop_table("node_runs")
    # ### end Alembic commands ###
