"""record what an inbound message replies to

Revision ID: 45fc7ffac350
Revises: 4ff2c8660d9e
Create Date: 2026-09-01 02:02:16.813487

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45fc7ffac350"
down_revision: str | Sequence[str] | None = "d96f607d0bb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reply_to", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("reply_to")

    # ### end Alembic commands ###
