"""the spine pass: pass_no, plans

Revision ID: 48632f7df1ca
Revises: d14a57090814
Create Date: 2026-09-30 00:34:00.691534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48632f7df1ca"
down_revision: str | Sequence[str] | None = "d14a57090814"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("replaces", sa.String(), nullable=True),
        sa.Column("cause", sa.String(), nullable=False),
        sa.Column("placement", sa.JSON(), nullable=False),
        sa.Column("body", sa.JSON(), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("gate_errors", sa.JSON(), nullable=False),
        sa.Column("pass_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("task_id", "version"),
    )
    # One row per pass under a key: the primary key gains `pass_no`. A new
    # table, the rows copied across (as pass 1), then swapped in — batch
    # mode's primary-key change warns that it may become an error.
    _swap_step_results(with_pass=True)

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("pass_no", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("pass_cause", sa.String(), server_default="first", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("pass_cause")
        batch_op.drop_column("pass_no")

    _swap_step_results(with_pass=False)

    op.drop_table("plans")
    # ### end Alembic commands ###


def _swap_step_results(*, with_pass: bool) -> None:
    """Rebuild `step_results` with or without `pass_no` in its key; on the way
    down, a key's rows from several passes keep the first pass's."""
    kept = [
        "task_id",
        "step_key",
        "step_id",
        "plan_version",
        "kind",
        "body",
        "created_at",
    ]
    columns = [
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("step_key", sa.String(), nullable=False),
        sa.Column("step_id", sa.String(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
    ]
    key = ["task_id", "step_key"]
    old = sa.table("step_results", *(sa.column(c) for c in [*kept, "pass_no"]))
    rows = sa.select(*(old.c[c] for c in kept))
    if with_pass:
        columns.append(
            sa.Column("pass_no", sa.Integer(), server_default="1", nullable=False)
        )
        key.append("pass_no")
    else:
        rows = rows.where(old.c.pass_no == 1)
    new = op.create_table(
        "step_results_new",
        *columns,
        sa.PrimaryKeyConstraint(*key, name="pk_step_results"),
    )
    op.execute(sa.insert(new).from_select(kept, rows))
    op.drop_table("step_results")
    op.rename_table("step_results_new", "step_results")
