"""keep model calls

Revision ID: 487ce9b6b7e8
Revises: 88aefe044e52
Create Date: 2026-08-31 14:19:11.553461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "487ce9b6b7e8"
down_revision: str | Sequence[str] | None = "88aefe044e52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("output", sa.String(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_calls_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_calls_message_id"), ["message_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_calls_message_id"))
        batch_op.drop_index(batch_op.f("ix_model_calls_created_at"))

    op.drop_table("model_calls")
    # ### end Alembic commands ###
