"""long-term notes

Revision ID: 4ff2c8660d9e
Revises: 68d8a57c8ade
Create Date: 2026-08-31 23:41:01.766205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff2c8660d9e'
down_revision: Union[str, Sequence[str], None] = '68d8a57c8ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category', 'text')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
