"""twelve kinds one table

Board `read-it-the-way-the-operator-does`, ticket 09: `memories` gains
`origin` (who is answerable for the row), `key` (a structured kind's natural
key) and `data` (its payload, checked against the kind's schema at write
time), plus one partial unique index holding each `(channel, kind, key)` to
one active row.

Every existing row was written by a model, so `origin` gets a server default
of `'model'`; `key` and `data` stay null. Nothing is destructive.

Revision ID: 527334fcabc2
Revises: 37048e489fc1
Create Date: 2026-09-18 15:26:55.954170

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "527334fcabc2"
down_revision: str | Sequence[str] | None = "37048e489fc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("origin", sa.String(), nullable=False, server_default="model")
        )
        batch_op.add_column(sa.Column("key", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("data", sa.JSON(), nullable=True))
        batch_op.create_index(
            "uq_memories_active_key",
            ["channel_id", "kind", "key"],
            unique=True,
            sqlite_where=sa.text("status = 'active' AND deleted_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_memories_active_key",
            sqlite_where=sa.text("status = 'active' AND deleted_at IS NULL"),
        )
        batch_op.drop_column("data")
        batch_op.drop_column("key")
        batch_op.drop_column("origin")

    # ### end Alembic commands ###
