"""an approved outbound row freezes its payload hash

Revision ID: 8fe3db098f79
Revises: c8434532382c
Create Date: 2026-09-23 01:24:58.284416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe3db098f79'
down_revision: Union[str, Sequence[str], None] = 'c8434532382c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_payload_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_column('approved_payload_hash')

    # ### end Alembic commands ###
