"""a room can be given a name

Non-destructive: one nullable column. `NULL` means unnamed, which is every
row until somebody types one, and is a different statement from `""` — the
route turns an empty string back into `NULL` rather than storing a name that
renders as nothing.

The column is the operator's own label. Nothing assembles it into a prompt
and no agent reads it, which is why it carries none of the escaping
obligations `channel_context`'s values do.

Revision ID: 93369d0ea345
Revises: f43e90e01c01
Create Date: 2026-09-07 12:05:10.129816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93369d0ea345'
down_revision: Union[str, Sequence[str], None] = 'f43e90e01c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
