"""an alert belongs to no task

Revision ID: 9b77911267e7
Revises: d96f607d0bb9
Create Date: 2026-08-31 19:01:00.806994

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b77911267e7"
down_revision: str | Sequence[str] | None = "d96f607d0bb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.alter_column("task_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.alter_column("task_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
