"""what node 0 already paid for

Revision ID: b4ba2cf5d60d
Revises: e7b9a1f3c2d4
Create Date: 2026-09-09 01:06:50.010139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ba2cf5d60d'
down_revision: Union[str, Sequence[str], None] = 'e7b9a1f3c2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_marks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('clarify_fields', sa.JSON(), nullable=False),
    sa.Column('clarify_because', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_marks')
    # ### end Alembic commands ###
