"""approval belongs to the row

Board read-it-the-way-the-operator-does, ticket 12 (finding A). Approval was
on the task, written once and never cleared, so every reply queued after the
first approved one was sendable unread. It moves to the outbox row. An
approved task's existing replies keep their approval, so nothing waiting to go
out is held back by the move — and nothing else becomes approved by it: only
kind `reply` needs approval, and the card that asked is not the answer.

Revision ID: c2b3bbe390ee
Revises: a423973bc96d
Create Date: 2026-09-18 14:53:23.172374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#: The kinds the outbox refuses without approval, as of this revision. Written
#: out rather than imported: a migration describes the database at one point
#: in time, and `friday.store.db._NEEDS_APPROVAL` may change after it.
_NEEDS_APPROVAL = ("reply",)

_tasks = sa.table(
    "tasks",
    sa.column("id", sa.Integer),
    sa.column("approved_at", sa.String),
    sa.column("approved_by", sa.String),
)
_outbox = sa.table(
    "outbox",
    sa.column("task_id", sa.Integer),
    sa.column("kind", sa.String),
    sa.column("approved_at", sa.String),
    sa.column("approved_by", sa.String),
)

# revision identifiers, used by Alembic.
revision: str = 'c2b3bbe390ee'
down_revision: Union[str, Sequence[str], None] = 'a423973bc96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approves', sa.Integer(), nullable=True))

    # Carry each approved task's approval onto the replies it already had,
    # before the task's columns go.
    def of_task(column):
        return (
            sa.select(column)
            .where(_tasks.c.id == _outbox.c.task_id)
            .scalar_subquery()
        )

    op.execute(
        _outbox.update()
        .where(
            _outbox.c.kind.in_(_NEEDS_APPROVAL),
            sa.exists().where(
                _tasks.c.id == _outbox.c.task_id,
                _tasks.c.approved_at.is_not(None),
            ),
        )
        .values(
            approved_at=of_task(_tasks.c.approved_at),
            approved_by=of_task(_tasks.c.approved_by),
        )
    )

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.VARCHAR(), nullable=True))

    # Back onto the task: a task is approved if any of its rows was, as of
    # the latest such approval. Lossy by nature — that was the defect.
    latest = (
        sa.select(_outbox.c.approved_at, _outbox.c.approved_by)
        .where(_outbox.c.task_id == _tasks.c.id, _outbox.c.approved_at.is_not(None))
        .order_by(_outbox.c.approved_at.desc())
        .limit(1)
    )
    op.execute(
        _tasks.update().values(
            approved_at=latest.with_only_columns(_outbox.c.approved_at).scalar_subquery(),
            approved_by=latest.with_only_columns(_outbox.c.approved_by).scalar_subquery(),
        )
    )

    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_column('approves')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
