"""drop dag_version (DBOS owns resume, ticket 06)

Revision ID: c8434532382c
Revises: c3e8d2a51b47
Create Date: 2026-09-23 00:31:32.587755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8434532382c'
down_revision: Union[str, Sequence[str], None] = 'c3e8d2a51b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dag_state', schema=None) as batch_op:
        batch_op.drop_column('dag_version')

    with op.batch_alter_table('node_runs', schema=None) as batch_op:
        batch_op.drop_column('dag_version')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dag_version', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('dag_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dag_version', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
