"""remember which message an outbound row became

Revision ID: d96f607d0bb9
Revises: 487ce9b6b7e8
Create Date: 2026-08-31 17:29:08.101585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96f607d0bb9'
down_revision: Union[str, Sequence[str], None] = '487ce9b6b7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_message_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_outbox_sent_message_id'), ['sent_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_sent_message_id'))
        batch_op.drop_column('sent_message_id')

    # ### end Alembic commands ###
